### ISSUE TITLE
Dialog Disappears on Device Rotation

### ISSUE THREAD

**Issue by reverse-unina** [Etar-Group/Etar-Calendar#121]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1-4:
1. Open Side Drawer
2. Click on Settings
3. Click on General Settings
4. Click on Quick responses
5. Click on:
a. Be there...
b. Go ahead...
c. Running...
d. Sorry...
6. Orientation Change

Sequence 5-6
1. Open Side Drawer
2. Click on:
a. Day
b. Week
3. Long Click on a day item
4. Orientation Change

**Comment by Grarie** [comment]
I can reproduce the mentioned issue. Even worse: the usual event creation dialog disappears every time you turn your device. This is more of a problem, since you sometimes want to use the turned keyboard.

To reproduce:
1. click on "+" to create a new event
2. turn your device

Expected behaviour:
- you see the event creation dialog in landscape mode

Actual behaviour:
- the event creation dialog closes

Further notes:
- Any typed data is gone and you have to recreate the whole event.
- It actually doesn't matter if you start in landscape or portrait mode, you just have to change the orientation of your device.
