### ISSUE TITLE
Event Time Shifts When Creating New Event by Double Tapping on Day View While "Use home time zone" Setting is On

### ISSUE THREAD

**Issue by landry314** [Etar-Group/Etar-Calendar#1264]
Yeah, that title is long, but that is exactly the bug...

When you have "Use home time zone" on and you double tap on the day view to create a new event at that time, it opens a new event window but the time it shows is shifted the amount of hours of the time zone difference away from where you tapped.

Let's say you are in Europe and your home time zone is in the Eastern USA, that is a 6 hour difference. EST = CEST - 6. If you tap on 6pm then it opens the new event editor and the start time is 12pm with the time zone as EST. Meaning, even though the display is showing in the home time zone, the new event creator treats the time tapped as the current time zone. This is not what the user would expect.

I'm pretty sure this is related to #382. While we are at it, it is related to #1260 too and all the issues I referenced inside of it because they are all due to the problem of "Use home time zone" being on and the calendar not knowing how to handle it. When an edit window is called from a calendar when "Use home time zone" is on it has some wrong data, whether is a shifted days in All-Day events or shifted hours in new events... Google threw this code together and didn't do a very good job with it.

**Comment by landry314** [comment]
This issue is related to issue #1194 in that it is only a problem when the "Use home time zone" setting is on.

**Comment by kingannoy** [comment]
I think I get how this is supposed to work. It allows you to say what timezone an appointment is in, and then the calender shows it's time in your "home" timezone. Nice if you do remote work in a different timezone from the workplace.

What I don't get is how this feature got activated by default and how the wrong timezone got configured. My default appointment timezone was suddenly UTC? I don't understand why. My phone is set to my actual timezone, UTC +1. 

This results in me making an appointment for 17:30. Saving it. It showing up in the overview at 18:30, when I open it up, it's shown as 18:30. When I edit, it's suddenly showing 17:30 again.

I was a hour late for a appointment due to this. I now need to manually check all appointments I made over the past weeks (months?) to see if there are any mistakes introduced in those too.

**Comment by lmamane** [comment]
No it is definitely not supposed to work like that and is a major trap for the user. The DayView/WeekView is in the home time zone (when that is activated). The user short-taps on an empty hour slot, and a "+" appears right there in the view, which is in the home timezone. The user then taps that "+" and suddenly that time slot is shifted? No. Just no.

I submitted GH-1404 pull request to fix this, but can't for the life of me get it linked here, nor by keyword nor in the sidebar of either this issue or the pull request.
