### ISSUE TITLE
Not possible to change calendar on an existing event

### ISSUE THREAD

**Issue by hariskar** [Etar-Group/Etar-Calendar#1266]
With Android 12 and Etar 1.0.30 it is not possible to change calendar on an existing event. The only solution is to delete it and re-create it.

**Comment by rparkins999** [comment]
I have code to do this in [my version](https://github.com/rparkins999/Etar-Calendar) , but it would be tricky to port back to this version because I have made so many other changes. Most of the difficulty in the code is in the many places where it has tests to stop you from trying to do this. The code to do it is actually quite simple: copy the `CalendarEvenModel`, change its calendar and convert it to a new event, save it, and delete the original event.

**Comment by olbotta** [comment]
instead of deleting it you could duplicate it, change the calendar of the new event, and delete the old one

**Comment by tiptoptom** [comment]
Duplication to #62
