### ISSUE TITLE
Widget has confusing dates

### ISSUE THREAD

**Issue by daa52** [Etar-Group/Etar-Calendar#1521]
The way that dates are presented in the widget is very confusing.  Right now, the header of the widget says on the first line "Thu" and on the second line "Nov 30".  This is in 2023 and the dates are correct.  At the top of the scrolling part, it says "Tomorrow, Thu, Nov 30".  Tomorrow is Dec 1, so I'm not sure what it says this.  There are no events today, which is Nov 30.  Underneath this first line of the scrolling part, it shows an event that is on Friday, Dec 1.  Underneath the event for Friday, Dec 1, it says Sat, Dec 2.  After that, it shows events on each day with the date under the last event for that day.  Yet, there is no "Fri, Dec 1" label under the event that is for that day.  

It would be most intuitive to print each date, that has events, with the events under the date.  The way it works now is a nonsense top label of the scrolling part and an incorrect date label for the first event followed by the date label under subsequent events.  

What I think is happening is that the "Tomorrow, Thu, Nov 30" label at the top of the scrolling part is coded incorrectly.  The "Tomorrow" is apparently referring to the event underneath it, though this is the opposite to the rest of the date labels where the date is under the events, not over.  The "Thu, Nov 30" refers to today, but there is nothing over it because there are no events today.  Whatever it is, it is very confusing.  I would really like to use the widget, but I get confused at which date goes with which event, so I have to open the whole calendar to check.  So, I just turned off the widget even though I'd like to use it.

**Comment by Kuebic** [comment]
It's not that it's confusing, it's wrong, especially when "Tomorrow" is followed by today's date. Considering it skips days where I don't have events, it's clear that the date above the event should be date of the event, but it's listing the date before.

I'm seeing the same thing as described above, just rewriting it.

Header: Today's Date "Wed Jan 24" (CORRECT)

Events for today appropriately slotted. (CORRECT)

"Tomorrow, Wed. Jan 24" (WRONG, it should say "Tomorrow, Thu, Jan 25")

Events for Thursday Jan 25.

"Thu, Jan 25"

Events for Friday Jan 26

"Tue, Jan 30"

Events for Wednesday Jan 31

**Comment by bisby** [comment]
https://github.com/Etar-Group/Etar-Calendar/pull/1469

AFAICT, this was fixed back in October and shipped in version 1.0.37

I'm still experiencing this as well on LineageOS, just because LineageOS seems to be not updating their core apps (but some common name somewhere means I can't just install Etar properly from f-droid)

You can see here in Lineage's fork of Etar that they haven't patched in the bug fixes:
https://github.com/LineageOS/android_packages_apps_Etar/blob/lineage-20.0/app/src/main/java/com/android/calendar/widget/CalendarAppWidgetModel.java#L53

There must be a guide somewhere, but I imagine fully uninstalling the core lineage calendar app should unblock being able to install the actually fixed and up to date Etar from the store of your choice.

**Comment by jspricke** [comment]
@Kuebic which Etar version do you use?

@bisby try https://github.com/Etar-Group/Etar-Calendar/issues/1438#issuecomment-1783056333

**Comment by bisby** [comment]
Hey thanks, that worked. I hate having to use ADB to solve android problems, but it did work. And also quite disappointing that LineageOS just doesn't keep their packages up to date if they're going to have conflicts. They should have a "pivot to F-Droid version" sort of tooling built in, but that's not a problem for this repo, I digress.

Thanks again.

**Comment by Kuebic** [comment]
@jspricke I'm using the version that comes with CalyxOS org.calyxos.etar, which I'm having a difficult time finding the version of. Last updated OTA in November, so it probably missed the October fix.

There is a [January Feature Update](https://calyxos.org/news/2024/01/27/january-feature-update/) coming, but there's a delay for my phone (Pixel 3) as they work on some bug.

Glad to hear it's fixed on the main branch... thought for sure I was on the latest. I'll just disable the OS version and get the fDroid version in the meantime. Cheers

**Comment by realwuffi** [comment]
This issue has been in LineageOS since October 23 or so. What would need to be done to get the latest ETAR package into LineageOS again? Version 1.0.36 has a nasty bug showing the calendar entries in the widget when you use a negative timezone (e. g. UTC -5) Please try to update that!

And I can't install the version from FDroid because the installation says:
Error 112: The system failed to install the package because it is attempting to define a permission that is already defined by some existing package.

Any help appreciated!

**Comment by jspricke** [comment]
@realwuffi as above, please try this to fix your LineageOS: https://github.com/Etar-Group/Etar-Calendar/issues/1438#issuecomment-1783056333

**Comment by realwuffi** [comment]
@jspricke Thanks, that worked. I was able to install the new ETAR 1.0.41 now.
But unfortunately the widget still shows the wrong dates... It still shows "Tomorrow Sun, Feb. 11"
even if that is today. I hoped the ETAR team got that fixed, seems like there is still an issue.
