### ISSUE TITLE
No synchronization with android 7

### ISSUE THREAD

**Issue by NeverWise** [Etar-Group/Etar-Calendar#159]
Etar does nothing when I press update on the menu. It doesn't download the new events from my calendar on google.
The only way to work is to synchronize the calendar with the Google Calendar application and then use Etar but, in this way, It is useless.
I have android 7.

Thanks for your job.

**Comment by jspricke** [comment]
Hi, on Android 5 using DAVdroid it's working fine for me, maybe Google changed something (sorry, don't have an Android 7 device till now). But actually I never use that button, as synchronization should be done automatically in the background.

**Comment by hhp211** [comment]
I experienced this issue too after removing both std android calendar and google calendar,
but after I installed the latest calendar sync app it was working properly again.
http://www.apkmirror.com/apk/google-inc/google-calendar-sync/
I used the 5.2.3-99827563-release  March 24, 2016 version

**Comment by paulle** [comment]
Can confirm. Using Android 7 and after removing both std android calendar and google calendar sync didn't work. I installed google-calendar-sync 5.2.3-99827563-release March 24, 2016 version (@hhp211 thank you for the hint and link). Now sync is working fine.

**Comment by andre-dierker** [comment]
Just for explaining, most/all calendar apps are syncing through Android OS. If you delete all related Google apps, you delete the ability to sync your calendars. It took me a whole night to find out. :smile:  :1st_place_medal:

**Comment by paulle** [comment]
Thank you for information.

Am 10. April 2017 15:24:57 MESZ schrieb Andre Dierker <notifications@github.com>:
>Just for explaining, most/all calendar apps are syncing through Android
>OS. If you delete all related Google apps, you delete the ability to
>sync your calendars. It took me a whole night to find out. :smile: 
>:1st_place_medal: 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Etar-Group/Etar-Calendar/issues/159#issuecomment-292948219

-- 
K-9 Mail

**Comment by jeepfromoil** [comment]
This isn't limited to Android 7.

Same bug on Android 6.0.1: with Google Calendar disabled, events created with Etar are **not** synced with Google Calendar.

There's no warning whatsoever and everything appear as if the events are saved/synced. This is a critical issue because the app doesn't indicate anywhere that the events are not saved/synced. Worst, the app says that "invitations will be sent" but this never happens.

Because of this bug, important business meetings couldn't be schedule on time.

Even weirder, all the events created with Etar while Google Calendar is disabled are delete when Calendar is re-enabled. In addition to the schedule issue reported above, this caused the loss of important data.

**Comment by jspricke** [comment]
@jeepfromoil what exactly did you disable?

**Comment by jeepfromoil** [comment]
The [Google Calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar&hl=en) application.

I have many other apps disabled (incl. Gmail, Chrome, Device Policy) but I assume they aren't the culprit since Etar started to work correctly as soon as I re-enabled Google Calendar.

**Comment by jeepfromoil** [comment]
@JonnyTech How do I do that?

**Comment by hhp211** [comment]
@jeepfromoil did you try installing the Google calendar sync app I have linked to above?
That is the fix you need to try.

**Comment by jeepfromoil** [comment]
I just did, and reinstalled Etar from F-Droid.

The thing is that when I open Etar after that, it asked for my calendar permissions (which I gave) and instantly crashed.  "Unfortunately, Etar  has stopped".

This happens every time I open the app now (deleting Etar's app data has no effect).

**Comment by JonnyTech** [comment]
> with Google Calendar disabled

In "Settings >> Apps ... Show System" you should see "Calendar Storage" and must not be disabled.

**Comment by jeepfromoil** [comment]
@JonnyTech Calendar Storage is enabled (with Contacts and Storage permissions)

**Comment by JonnyTech** [comment]
Go to "Calendar Storage" above and click "Storage" then "Clear Data". This should reset the onboard calendar. The go to "Settings >> Accounts" where you should remove then recreate your Google account. Reboot then try syncing again.

**Comment by jeepfromoil** [comment]
I cleared the data in Calendar Storage and Etar, removed my Google accounts at the OS level, and re-added it (from Android settings > Account). As soon as I added my Google account, I got the "Unfortunately, Etar has stopped" popup. When I open Etar, it opens a Google account sign-in page which says I can't sign into my account because it's already added to the device.

**Comment by JonnyTech** [comment]
It sounds like a ROM problem. Which variant are you running? Are you rooted? Have you changed any system apps or permissions? It is working for me on both Marshmallow and Nougat. If you are rooted then there are more options open to diagnosing and fixing your Google Apps subsystem.

**Comment by jeepfromoil** [comment]
Device:

* Nexus 5 (not rooted)
* Android version: 6.0.1
* Baseband version M8974A-2.0.50.2.30
* Kerbel version: .4.0-gcf10b7e
* Build number: M4B30Z

Apps disabled (incl. System): Calculator, Camera, Chrome, Clock, Cloud
Print, Google Messenger, Device Policy, Docs, Drive, Fit, Gmail, Play
Books, Play Movies, Play Music, Newsstand, Google+, Hangouts, Keep, Maps,
News & Weather, Photos, Sheets, Slides

**Comment by JonnyTech** [comment]
I would start by enabling *ALL* of your disabled apps therefore getting the phone close to a known good starting point. Google applications can be a bit finicky and disabling one may produce side-effects in another. Then reboot and provide a logcat during synchronisation.

**Comment by jspricke** [comment]
I had a look at Android 6 and indeed Google fused it's calendar sync adapter into the general Calendar. As this has nothing to do with Etar (note that Etar just views and edits the internal DB and is not a sync adapter) and there are enough alternatives to Google discussed in this thread, I'm closing this.
