### ISSUE TITLE
Etar wont start if denying access to sd card

### ISSUE THREAD

**Issue by mueller-ma** [Etar-Group/Etar-Calendar#222]
I get the error "etar needs read/write permissions to calendar" even of it has

**Comment by xsoh** [comment]
Hello,
What version of Etar you are using?

thanks

**Comment by mueller-ma** [comment]
Latest 1.0.12 from fdroid

**Comment by mueller-ma** [comment]
I think introduced by 45e5aab63dbe17e5e17fe554629b01e59e1e5d27

**Comment by jspricke** [comment]
The error (or rather info) message is still because of the previous request for the calendar access. It's just floating around still. The sd card permission is needed to fill the event import dialog in the background. We could move it to the import dialog, but I guess that it wouldn't work at the at the first start then.

**Comment by jspricke** [comment]
This should be fixed by #287 as well.
