### ISSUE TITLE
Collected Feedback

### ISSUE THREAD

**Issue by ulph0** [Etar-Group/Etar-Calendar#423]
Hi. I <3 Etar. Thanks for it! 2 Things

- Horizontal Zooming would be very very nice! Often i have so much events in a row that i can't read 
  their titles. Or tap on them, because the boxes are to thin.
- Often when i add a new event, when i am ready and go back they are doubled. Like one version was 
  saved when i started editing the event and one when i finished it. Maybe i do something wrong, but 
  then its maybe to easy to do it wrong.
- When i saved an event i can't change the calendar afterwards, when i accidentially saved it to the 
   wrong one.

Regards, u.

**Comment by jspricke** [comment]
Hi, thanks for you feedback. Your issues are already mentioned in the tracker:
* Zoom: #119 
* double creation should be fixed in the new version (1.0.14): #216 
* change calendar: #62 and #101 

Please search the issue tracker before creating new issues. Also please open individual issues per problems, so we can track and close them one by one.

Closing as all issues are already covered.
