### ISSUE TITLE
What does "إِيتَار" mean?

### ISSUE THREAD

**Issue by mueller-ma** [Etar-Group/Etar-Calendar#494]
Hey,
your Readme says "Etar (from Arabic: إِيتَار)". Can you explain what the arabic word means or where it comes from?

**Comment by xsoh** [comment]
Well, I chose the word Etar because I wanted an easy word to write and/or to speech in many languages. I didn't actually care about the meaning it self. 

From the [dictionary](https://www.almaany.com/ar/dict/ar-ar/%D8%A3%D9%8E%D9%88%D8%AA%D9%8E%D8%B1%D9%8E/), the word `إِيتَار` is from the root word ` أَوتَرَ` or Awtar.  And when "a person Awtar the bow" then he assembled a [bowstring](https://en.wikipedia.org/wiki/Bowstring) for the bow.
So let's say it mainly means: **Bowstringation**. 🏹
