### ISSUE TITLE
Search Icon

### ISSUE THREAD

**Issue by imcmjha** [Etar-Group/Etar-Calendar#769]
Thanks for creating such a wonderful app. I've one feature request. 
There is already an option to search but it would be better if there would be a search icon in top menu beside the Today icon.
Thanks.

**Comment by Cwpute** [comment]
Hi, sorry to bring back this topic. I'm using Etar 1.0.48 and i can't see the search icon.
Has this feature been added but my phone has an issue, or has this issue been closed without applied changes ?

This would be very welcome, i've just now discovered Etar's search function, because i had never went into the 3-dots menu.
It would also lower the amount of taps needed to access this feature : when you have lots of events programmed like i do, it can be VERY OFTEN used (if you even know it exists 😭), so any improved access is welcome.

**Comment by Cwpute** [comment]
It seems i'm not the only one who missed this feature as issue #1437 suggests
