### ISSUE TITLE
Custom storage locaton for offline calendar

### ISSUE THREAD

**Issue by charsi** [Etar-Group/Etar-Calendar#991]
Hi, thanks for the app!

Would it be possible to implement a custom storage location for storing a offline calendar on the phone? I haven't looked but if this is just an ics file I'd like to sync it with syncthing. 

Would you take a pull request for this ?

**Comment by jspricke** [comment]
Hi,

that functionality is already available by using for example ICSx⁵:
https://f-droid.org/packages/at.bitfire.icsdroid/

See also:
https://github.com/Etar-Group/Etar-Calendar#how-to-use-etar

I don't think adding the functionality to Etar makes sense.

**Comment by charsi** [comment]
I looked at ICSx⁵ but it doesn't support two way sync. This is mentioned in their FAQ -  https://icsx5.bitfire.at/faq/

My other option is to use [DecSyncCC](https://www.f-droid.org/en/packages/org.decsync.cc/) which I am already using for contacts. But for thunderbird to sync with it I'll need to run [Radicale](https://radicale.org) server on my laptop at all times. 

It will be great if I can find a calendar app that can write directly to an ics file.

**Comment by StefanRastocky** [comment]
Hello, has there been any progress made on this issue? The commenter was right to point out that ICSx5 does not support writing to an ics file. Can you please address the fact that your original response did not offer a valid solution and let us know if you are planning to implement this functionality in the future? There is a lot of us who would like to use syncthing to sync our one .ics file between devices rather than having to run a personal caldav server for essentially just sharing one file.
